/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Andrey
 */
public class MixGUI extends javax.swing.JFrame {

    /**
     * Creates new form MixGUI
     */
    public MixGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        honeyImage = new javax.swing.JLabel();
        herbsImage = new javax.swing.JLabel();
        clayImage = new javax.swing.JLabel();
        mineralImage = new javax.swing.JLabel();
        potionImage = new javax.swing.JLabel();
        incenseImage = new javax.swing.JLabel();
        gemsImage = new javax.swing.JLabel();
        lifeelixirImage = new javax.swing.JLabel();
        manacrystalImage = new javax.swing.JLabel();
        philosopherstoneImage = new javax.swing.JLabel();
        slotPanel1 = new javax.swing.JPanel();
        slotPanel2 = new javax.swing.JPanel();
        mixButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        honeyCount = new javax.swing.JLabel();
        herbsCount = new javax.swing.JLabel();
        clayCount = new javax.swing.JLabel();
        mineralCount = new javax.swing.JLabel();
        potionCount = new javax.swing.JLabel();
        incenseCount = new javax.swing.JLabel();
        gemsCount = new javax.swing.JLabel();
        lifeelixirCount = new javax.swing.JLabel();
        manacrystalCount = new javax.swing.JLabel();
        philosopherstoneCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mix Item");
        setPreferredSize(new java.awt.Dimension(800, 600));

        honeyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/honey.png"))); // NOI18N

        herbsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/herbs.png"))); // NOI18N

        clayImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clay.png"))); // NOI18N

        mineralImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mineral.png"))); // NOI18N

        potionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/potion.png"))); // NOI18N

        incenseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incense.png"))); // NOI18N

        gemsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gems.png"))); // NOI18N

        lifeelixirImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lifeelixir.png"))); // NOI18N

        manacrystalImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manacrystal.png"))); // NOI18N

        philosopherstoneImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/philosopherstone.png"))); // NOI18N

        slotPanel1.setBackground(new java.awt.Color(255, 255, 153));
        slotPanel1.setPreferredSize(new java.awt.Dimension(85, 85));

        javax.swing.GroupLayout slotPanel1Layout = new javax.swing.GroupLayout(slotPanel1);
        slotPanel1.setLayout(slotPanel1Layout);
        slotPanel1Layout.setHorizontalGroup(
            slotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        slotPanel1Layout.setVerticalGroup(
            slotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        slotPanel2.setBackground(new java.awt.Color(255, 255, 153));
        slotPanel2.setPreferredSize(new java.awt.Dimension(85, 85));

        javax.swing.GroupLayout slotPanel2Layout = new javax.swing.GroupLayout(slotPanel2);
        slotPanel2.setLayout(slotPanel2Layout);
        slotPanel2Layout.setHorizontalGroup(
            slotPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        slotPanel2Layout.setVerticalGroup(
            slotPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        mixButton.setText("Mix");
        mixButton.setMaximumSize(new java.awt.Dimension(49, 23));
        mixButton.setPreferredSize(new java.awt.Dimension(55, 23));
        mixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(slotPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(slotPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(incenseCount)
                        .addGap(127, 127, 127)
                        .addComponent(gemsCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lifeelixirCount)))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manacrystalCount)
                        .addGap(97, 97, 97)
                        .addComponent(philosopherstoneCount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backButton)
                            .addComponent(mixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(honeyCount)
                        .addGap(127, 127, 127)
                        .addComponent(herbsCount)
                        .addGap(127, 127, 127)
                        .addComponent(clayCount)
                        .addGap(124, 124, 124)
                        .addComponent(mineralCount)
                        .addGap(128, 128, 128)
                        .addComponent(potionCount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(honeyImage)
                            .addComponent(incenseImage))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(herbsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gemsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clayImage)
                            .addComponent(lifeelixirImage))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mineralImage)
                            .addComponent(manacrystalImage))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(philosopherstoneImage)
                            .addComponent(potionImage))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(honeyImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(herbsImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clayImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mineralImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(potionImage, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(honeyCount)
                    .addComponent(herbsCount)
                    .addComponent(clayCount)
                    .addComponent(potionCount)
                    .addComponent(mineralCount))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incenseImage)
                    .addComponent(gemsImage)
                    .addComponent(lifeelixirImage)
                    .addComponent(manacrystalImage)
                    .addComponent(philosopherstoneImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incenseCount)
                    .addComponent(lifeelixirCount)
                    .addComponent(philosopherstoneCount)
                    .addComponent(manacrystalCount)
                    .addComponent(gemsCount))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slotPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backButton))
                    .addComponent(slotPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MixGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MixGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel clayCount;
    private javax.swing.JLabel clayImage;
    private javax.swing.JLabel gemsCount;
    private javax.swing.JLabel gemsImage;
    private javax.swing.JLabel herbsCount;
    private javax.swing.JLabel herbsImage;
    private javax.swing.JLabel honeyCount;
    private javax.swing.JLabel honeyImage;
    private javax.swing.JLabel incenseCount;
    private javax.swing.JLabel incenseImage;
    private javax.swing.JLabel lifeelixirCount;
    private javax.swing.JLabel lifeelixirImage;
    private javax.swing.JLabel manacrystalCount;
    private javax.swing.JLabel manacrystalImage;
    private javax.swing.JLabel mineralCount;
    private javax.swing.JLabel mineralImage;
    private javax.swing.JButton mixButton;
    private javax.swing.JLabel philosopherstoneCount;
    private javax.swing.JLabel philosopherstoneImage;
    private javax.swing.JLabel potionCount;
    private javax.swing.JLabel potionImage;
    private javax.swing.JPanel slotPanel1;
    private javax.swing.JPanel slotPanel2;
    // End of variables declaration//GEN-END:variables
}
